ALTER TABLE COMPRA DROP CONSTRAINT FK_COMPRA_PROVEEDOR
ALTER TABLE COMPRADETALLE DROP CONSTRAINT FK_COMPRADETALLE_PRODUCTO
ALTER TABLE COMPRADETALLE DROP CONSTRAINT FK_COMPRADETALLE_COMPRA
ALTER TABLE VENTA DROP CONSTRAINT FK_VENTA_CLIENTE
ALTER TABLE VENTADETALLE DROP CONSTRAINT FK_VENTADETALLE_VENTA
ALTER TABLE VENTADETALLE DROP CONSTRAINT FK_VENTADETALLE_PRODUCTO
DROP TABLE PERSONA
DROP TABLE PRODUCTO
DROP TABLE REGISTROPAGO
DROP TABLE COMPRA
DROP TABLE COMPRADETALLE
DROP TABLE VENTA
DROP TABLE VENTADETALLE
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
